erDiagram

    profiles {
        uuid id PK
        text email
        text password
        text name
        text photo_url
        text biography
        text telephone
        timestamptz created_at
    }

    announces {
        uuid id PK
        uuid user_id FK
        text image_url
        text title
        text description
        numeric price
        bool donation
        text category
        timestamptz created_at
    }

    profiles ||--o{ announces : "creates"
